### ISSUE TITLE
Spool Manager overlaps panel below

### ISSUE THREAD

**Issue by Xiondewah** [LazeMSS/OctoPrint-UICustomizer#157] opened 2021-05-27 06:42 UTC
Updated to 0.1.5.9 which has fixed the layout of the edit/add spool manager - so thanks - but still have the problem where spool manager ui overlaps any panel below (so I've had to position it at the bottom of the left hand frame.

:-)

**Comment by LazeMSS** [comment] 2021-05-27 07:15
Screenshot?

**Comment by Xiondewah** [comment] 2021-05-27 07:16
Sorry - forgot!
![image](https://user-images.githubusercontent.com/50043329/119782290-e5e7b580-bec3-11eb-9cad-49feb80b1eaf.png)

**Comment by LazeMSS** [comment] 2021-05-27 07:19
Yes thats really not a bug in UI Customizer - that panel has a "nobr" tag - so the browser is told to never make linebreaks. This should be fixed in the spool manager plugin - no break is really no good for mobile/responsive layouts. As stated in https://github.com/OllisGit/OctoPrint-SpoolManager/issues/142 I will try and do a bit of revamp of the UI together with OllisGit.

**Closed** 2021-05-27 07:19 UTC
Labels: wontfix

**Comment by Xiondewah** [comment] 2021-05-27 07:21
This is frustrating because I posted it on OllisGit's hub and he said it should be with you - but thanks, hopefully the 2 of you will be able to sort it out between you.

**Comment by OllisGit** [comment] 2021-05-27 22:10
Hey @Xiondewah,

I closed your ticket, because it was duplicated. And I entered a link to the other ticket where LazeMSS is also involved in the discussion.
See your orig. Ticket:  https://github.com/OllisGit/OctoPrint-SpoolManager/issues/171

I never said that the issue must be solved by @LazeMSS !

**Comment by OllisGit** [comment] 2021-05-27 22:21
Btw. the br-element will be removed in the next release.

**Comment by LazeMSS** [comment] 2021-05-28 05:38
> Hey @Xiondewah,
> 
> I closed your ticket, because it was duplicated. And I entered a link to the other ticket where LazeMSS is also involved in the discussion.
> See your orig. Ticket: [OllisGit/OctoPrint-SpoolManager#171](https://github.com/OllisGit/OctoPrint-SpoolManager/issues/171)
> 
> I never said that the issue must be solved by @LazeMSS !

No panic @OllisGit  we will work out a good solution together ;)

**Comment by Xiondewah** [comment] 2021-05-28 06:27
Thank you both - the two plugins are so useful!
