### ISSUE TITLE
Conflicts with another plugin called Printjob History

### ISSUE THREAD

**Issue by blownco** [LazeMSS/OctoPrint-UICustomizer#131] opened 2021-04-14 04:28 UTC
## Description
**This plugin conflicts with another plugin called printjob history.

Describe your problem?
The problem occurs when printjob history is installed all the columns become messed up and it shows the webcam multiple times. 

Can you recreate it?
yes install this plugin and prinjob history 

https://github.com/OllisGit/OctoPrint-PrintJobHistory

Did you try disabling plugins?
yes

Did you remember to update the subject?**
<hr>

**Plugins installed**
- Bed Visualizer[bedlevelvisualizer] v1.0.1
- Cura Thumbnails[UltimakerFormatPackage] v0.2.2
- DisplayLayerProgress Plugin[DisplayLayerProgress] v1.26.0
- FileManager[filemanager] v0.1.6
- Marlin EEPROM Editor[eeprom_marlin] v3.0.2
- Octoprint-Display-ETA[display_eta] v1.1.3
- OctoRant[octorant] v1.2.3
- Preheat Button[preheat] v0.7.2
- Printoid Plugin[printoid] v1.0.2
- PrintTimeGenius Plugin[PrintTimeGenius] v2.2.7
- PrusaSlicer Thumbnails[prusaslicerthumbnails] v0.1.4
- Resource Monitor[resource_monitor] v0.3.3
- SpoolManager Plugin[SpoolManager] v1.3.3
- Terminal Messaging[terminalmessaging] v0.1.0
- Top Temp[toptemp] v0.0.1.4
- **UI Customizer[uicustomizer] v0.1.5.5**

**UI Customizer settings**
- addWebCamZoom: true
- centerTopIcons: true
- compactMenu: false
- compressTempControls: true
- disableTermInactive: false
- filesFullHeight: true
- fixedFooter: true
- fixedHeader: true
- fluidLayout: true
- gcodeFullWidth: true
- hideGraphBackground: true
- hideMainCam: false
- mainTabsCustomize: true
- navbarplugintempfix: true
- responsiveMode: true
- themeLocal: true

**Software versions**
- OctoPrint 1.5.3
- Python 3.7.3
- OctoPi 0.18.0

**Browser**
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36

**Comment by LazeMSS** [comment] 2021-04-14 06:39
Duplicate of: https://github.com/LazeMSS/OctoPrint-UICustomizer/issues/129

**Closed by LazeMSS** 2021-04-14 06:39 UTC
