### ISSUE TITLE
Request - Split Main tabs

### ISSUE THREAD

**Issue by AaronLee115** [LazeMSS/OctoPrint-UICustomizer#63] opened 2021-01-08 01:34 UTC
Can we have the option to split up the main tabs so that we can ,for example, view the controls menu and temperature at the same time?

Thanks,

**Comment by LazeMSS** [comment] 2021-01-08 05:31
Duplicate of : https://github.com/LazeMSS/OctoPrint-UICustomizer/issues/30

**Closed by LazeMSS** 2021-01-08 05:31 UTC
