### ISSUE TITLE
Sidebar webcam and popout rotation not working

### ISSUE THREAD

**Issue by alefchak** [LazeMSS/OctoPrint-UICustomizer#119] opened 2021-03-24 03:03 UTC
The webcam sidebar image is no longer respecting the "Flip webcam horizontally" and "Flip webcam vertically" options in the main Octoprint settings.

I have both of these settings checked, and while the main webcam display appears correct, the sidebar camera is not.

Additionally, if I click on the pop out icon in the corner of either, the large display is also incorrect (upside down).

I have the same issue with all browsers I've tried - Chrome on macOS, Windows, and Android, as well as Safari on macOS.

![image](https://user-images.githubusercontent.com/96546/112247516-d087ae00-8c2a-11eb-8bdd-5f579e895a79.png)

**Comment by LazeMSS** [comment] 2021-03-24 07:19
Sorry - I can't replicate this in anyway on my platform.

**Comment by alefchak** [comment] 2021-03-25 00:10
I disabled plugins until I the behavior changed - it appears to be an interaction with the [Dashboard](https://plugins.octoprint.org/plugins/dashboard/) plugin. I don't think it modifies the webcam but it does have an option to add it to its display.

**Comment by LazeMSS** [comment] 2021-03-25 08:39
Maybe they implement something extra on the webcam container etc. that causes my plugin to loose the options. I will try when I have time and either fix it or report it to the dashboard team.

**Comment by LazeMSS** [comment] 2021-03-25 19:59
I tried install the dashboard - i have no problems. What kind of webcam stream are you using?

And can you try and run 
`$("#IUCWebcamContainerInner img").attr('class')`

from the web developer console?

**Comment by LazeMSS** [comment] 2021-03-25 20:00
From my printer 👍 
![image](https://user-images.githubusercontent.com/69049371/112535798-fccb3800-8dac-11eb-9747-9e68ab2f54aa.png)

My settings:
![image](https://user-images.githubusercontent.com/69049371/112535899-153b5280-8dad-11eb-91cb-d7bf6e69117f.png)

**Comment by alefchak** [comment] 2021-03-26 00:23
> I tried install the dashboard - i have no problems. What kind of webcam stream are you using?
> 
> And can you try and run
> `$("#IUCWebcamContainerInner img").attr('class')`
> 
> from the web developer console?

I'm using a Raspberry Pi camera module. I am have `camera="raspi"` and `camera_raspi_options="-x 1296 -y 972 -fps 30 -quality 100"` set in the Octoprint configuration, and the following settings in the web UI:

![image](https://user-images.githubusercontent.com/96546/112559357-38fb9a00-8da7-11eb-923e-089c54479948.png)

`$("#IUCWebcamContainerInner img").attr('class')` is returning `undefined` while the Dashboard plugin is active, but `"flipH flipV"` while it's disabled.

I did notice that if I uncheck the flip image options, save, recheck them, and save, the appropriate `"flipH flipV"` classes are applied, but go away when the page is refreshed.

**Comment by LazeMSS** [comment] 2021-03-26 06:46
Thanks I have no Idea why this is happening but will try and look.

Btw there is a way of flipping the video feed directly in the RPI driver. It will fix your problems for now I think. If you know your way around bash/shell then it might be easier.

**Comment by LazeMSS** [comment] 2021-03-26 08:06
I tried same settings - I never have this problem.

Btw. try this from bash/shell on rpi:
```
sudo service webcamd stop
cd /home/pi/mjpg-streamer
./mjpg_streamer -i "./input_raspicam.so -hf -vf" -o "./output_http.so -w ./www"
```
This should flip the camera etc: https://github.com/jacksonliam/mjpg-streamer/blob/master/mjpg-streamer-experimental/plugins/input_raspicam/README.md

**Comment by Dag0d** [comment] 2021-03-26 23:12
I do have a similar problem, the sidebar image is fine but if I enlarge the picture it's upside down. if I check the code, the "img class="flipH flipV"" is missing.

**Comment by LazeMSS** [comment] 2021-03-27 10:10
@Dag0d  what type of cam etc?

**Comment by Dag0d** [comment] 2021-03-27 13:53
@LazeMSS a normal raspberry pi v2 camera

**Comment by LazeMSS** [comment] 2021-03-28 08:15
There should be no difference between the hardware camera types.

@Dag0d  any other plugins installed that might affect the camera?

**Comment by Dag0d** [comment] 2021-03-28 08:55
You are right, I did some testing and the error only occurs when the dashboard plugin is enables as well.

**Comment by LazeMSS** [comment] 2021-03-28 13:50
I can't recreate it no matter what i do - it must be something about the order of plugins loading etc.

@Dag0d + @alefchak can you try and post your plugins so we can look for matches and maybe its a combination of plugins

**Comment by tutanra** [comment] 2021-03-28 16:45
Show in dashboard github, it solves, only occurs when webcam widget in dashboard is disabled.

**Comment by Dag0d** [comment] 2021-03-28 19:04
@tutanra this did the trick!

**Comment by LazeMSS** [comment] 2021-03-28 21:15
> Show in dashboard github, it solves, only occurs when webcam widget in dashboard is disabled.
> 
> [j7126/OctoPrint-Dashboard#268](https://github.com/j7126/OctoPrint-Dashboard/issues/268)
> 
> This is the temporary fix : https://github.com/j7126/OctoPrint-Dashboard/archive/refs/heads/development.zip

Ohh awesome. I made a generic feature request because I noticed your naming did conflict on some items but I was still trying to find the cause. Closing this one when you release it ok?

**Comment by LazeMSS** [comment] 2021-04-08 07:21
@tutanra when will this be released/include in the main ?

**Comment by LazeMSS** [comment] 2021-04-25 07:47
Done - I can't fix this

**Closed by LazeMSS** 2021-04-25 07:47 UTC
Labels: help wanted
