### ISSUE TITLE
webcam problems in ver 0.1.8.7

### ISSUE THREAD

**Issue by CBDesignS** [LazeMSS/OctoPrint-UICustomizer#234] opened 2022-02-18 16:38 UTC
## Description
**ENTER DESCRIPTION HERE
Describe your problem?

Webcam preview in right part of screen just says Loading webcam until it gives up. Cam pictures are live if the option to display in control menu is unticked as it should be but if the box is ticked to hide then it never comes back in the other preview window.. This is brand new to this release of 0.1.8.7

![cam1](https://user-images.githubusercontent.com/54717994/154724457-574d52f0-a6e3-4d7d-be29-4bf9fc2f4e32.jpg)
![cam2](https://user-images.githubusercontent.com/54717994/154724585-911e1516-3795-4c04-a469-e2b6d6985fdf.jpg)
![cam3](https://user-images.githubusercontent.com/54717994/154724599-f5f9d5bb-559e-4d8e-be8e-d98c644778f4.jpg)

What is the problem?
Can you recreate it?
Did you try disabling plugins?
Did you remember to update the subject?**
<hr>

**Plugins installed**
- Active Filters Extended[active_filters_extended] v0.1.0
- Arc-Welder[arc_welder] v1.1.0rc4
- Bed Visualizer[bedlevelvisualizer] v1.1.1
- BLTouch Plugin[BLTouch] v0.3.4
- Camera Settings[camerasettings] v0.3.1
- Custom Control Editor[customControl] v0.2.2
- Filament Manager[filamentmanager] v1.9.1
- Firmware Updater[firmwareupdater] v1.13.1
- Floating Navbar[floatingnavbar] v0.3.7
- LightsOut[lightsout] v0.1.2
- M117 Speech Synthesis[M117SpeechSynthesis] v0.5.3
- Marlin EEPROM Editor[eeprom_marlin] v3.2.0
- Navbar Temperature Plugin[navbartemp] v0.14
- OneDrive Backup[onedrive_backup] v1.0.1
- PrettyGCode[prettygcode] v1.2.4
- PrintTimeGenius Plugin[PrintTimeGe

nius] v2.2.8
- Slicer Thumbnails[prusaslicerthumbnails] v1.0.0
- Terminal Messaging[terminalmessaging] v0.1.0
- **UI Customizer[uicustomizer] v0.1.8.7**
- WS281x LED Status[ws281x_led_status] v0.8.0

**UI Customizer settings**
- addWebCamZoom: false
- centerTopIcons: true
- compactMenu: true
- compressTempControls: false
- disableTermInactive: false
- filesFullHeight: true
- fixedFooter: false
- fixedHeader: true
- fluidLayout: true
- gcodeFullWidth: false
- hideGraphBackground: false
- hideMainCam: true
- mainTabsCustomize: true
- navbarplugintempfix: false
- responsiveMode: true
- saveAccordions: false
- themeLocal: false

**Software versions**
- OctoPrint 1.7.3
- Python 3.7.3
- OctoPi 0.18.0

**Browser**
- Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0

**Comment by LazeMSS** [comment] 2022-02-18 18:08
HLS or normal mpjeg cam stream - what is the cam URL?

**Comment by LazeMSS** [comment] 2022-02-18 18:10
Bug found - thanks for reporting will try and fix asap - turn on "Float/Fullscreen webcam" as a workaround

**Comment by CBDesignS** [comment] 2022-02-19 01:52
it was just the normal mpjeg cam stream @LazeMSS. thx

**Comment by ManuelMcLure** [comment] 2022-02-19 17:07
I'm also seeing camera issues. It works on first page load to show the small camera in the corner, then I can zoom the camera and it works, but if I then unzoom the camera the feed is gone until I reload the page completely. This is Chrome on both Windows 10 and MacOS 12.

**Comment by LazeMSS** [comment] 2022-02-19 22:25
> I'm also seeing camera issues. It works on first page load to show the small camera in the corner, then I can zoom the camera and it works, but if I then unzoom the camera the feed is gone until I reload the page completely. This is Chrome on both Windows 10 and MacOS 12.

do you have the webcam hidden on control tab or not?

**Comment by ManuelMcLure** [comment] 2022-02-19 22:26
Yes, I do.
![image](https://user-images.githubusercontent.com/9875787/154821115-ece00a5a-59f7-43ea-a41b-57209c7324ce.png)

**Comment by CBDesignS** [comment] 2022-02-19 23:44
> Bug found - thanks for reporting will try and fix asap - turn on "Float/Fullscreen webcam" as a workaround

I tried Using this option as you suggested and it is causing the freeze up of the stream on control tab and on preview window.

**Comment by LazeMSS** [comment] 2022-02-20 08:26
@ManuelMcLure  can you try and use the developer tools to see if the webcam stream stop (under the network tab)

**Comment by LazeMSS** [comment] 2022-02-20 10:51
> > Bug found - thanks for reporting will try and fix asap - turn on "Float/Fullscreen webcam" as a workaround
> 
> I tried Using this option as you suggested and it is causing the freeze up of the stream on control tab and on preview window.

Thats really strange. I have no problems on my installations.

**Comment by CBDesignS** [comment] 2022-02-20 19:00
> > > Bug found - thanks for reporting will try and fix asap - turn on "Float/Fullscreen webcam" as a workaround
> > 
> > 
> > I tried Using this option as you suggested and it is causing the freeze up of the stream on control tab and on preview window.
> 
> Thats really strange. I have no problems on my installations.

I use http://192.168.0.254/webcam/?action=stream to remote view on my local lan via vlc so I opened the link in a different browser tab to monitor whats going on.
 
When the stream freezes up if I refresh the browser tab http://192.168.0.254/webcam/?action=stream the stream starts again in that window and vanishes from the octo preview window then reloads the stream plays as it should untill it freezes and goes again. I repeat the browser tab refresh and it starts to live stream and octo reloads. Freeze can be random. 30 seconds, 5 mins, etc there seems to be no defined time
![cam4](https://user-images.githubusercontent.com/54717994/154859097-59bb39a1-3550-48cf-a807-2258e648865e.jpg)
![cam4](https://user-images.githubusercontent.com/54717994/154859107-afbfeabe-6c07-4e2e-af01-0ae4800ad9cc.jpg)

This is a different machine from the one I originally started this bug report on. it is (raspbian bullseye InRelease) that I just finnished off setting up, the other machine is still on buster and both display very simmilar problems. both are up to date o/s & rpi firmware wise.

**Comment by LazeMSS** [comment] 2022-02-21 08:43
Does the stream also stop in VLC when you are having the problems.
The latest update remove ALL the previous "hacks" to make the streams be a copy and now only rely on the main Octoprint stuff.

If you disable hide the main webcam and have the control tab active does this still happen?

**Comment by ManuelMcLure** [comment] 2022-02-21 18:17
With the camera enabled in the control tab, before zooming:
![image](https://user-images.githubusercontent.com/9875787/155008215-b7fcae2e-fc8e-4a3f-9994-42447b8ae8e6.png)
After zooming:
![image](https://user-images.githubusercontent.com/9875787/155008265-a8dae885-bd3d-4d14-8299-431dcf8bee23.png)

With camera disabled in the control tab, before zooming:
![image](https://user-images.githubusercontent.com/9875787/155008355-5f375324-82ac-42ea-86ff-a03317c19545.png)
After zooming:
![image](https://user-images.githubusercontent.com/9875787/155008395-3d7d6fdc-842c-4053-aebf-c2d63f8350d2.png)

**Comment by CBDesignS** [comment] 2022-02-21 19:52
> Does the stream also stop in VLC when you are having the problems. The latest update remove ALL the previous "hacks" to make the streams be a copy and now only rely on the main Octoprint stuff.
> 
> If you disable hide the main webcam and have the control tab active does this still happen?

@LazeMSS the vlc stream plays as it should. I have just tried a test print to find out and while the stream in octo is frozen the vlc stream in my house was working great.

**Comment by LazeMSS** [comment] 2022-02-24 11:04
@ManuelMcLure  could you post the plugins you have installed? Just looking for a pattern here

**Comment by LazeMSS** [comment] 2022-02-24 11:08
If anyone of you could post a short video I would really like to see it.

**Comment by LazeMSS** [comment] 2022-02-24 13:29
I'm 99% sure the bug is related to prettygcode - I have submitted a bug report and a PR to fix it for that plugin (https://github.com/Kragrathea/OctoPrint-PrettyGCode/pull/135)

Until then you can use my the PR version pretty gcode by manual installing the plugin from: https://github.com/LazeMSS/OctoPrint-PrettyGCode/archive/refs/heads/id-bugfix.zip
(for help see: https://plugins.octoprint.org/help/installation/ under "Via the URL and the Plugin Manager")

**Comment by CBDesignS** [comment] 2022-02-24 13:54
So far so good with the prettygcode patch @LazeMSS . My cam would have frozen by now and its still playing. Just started a 46min print and will keep fingers crossed

**Comment by CBDesignS** [comment] 2022-02-24 14:31
will not edit orig post .. here is a link to a short video . the second the video stops is when it froze up again. I tried to keep it short.

link to video  https://1drv.ms/v/s!AisctMQ7h6vWn_MbL7xzBJ6riniPGA?e=IRRZ5n

**Comment by ManuelMcLure** [comment] 2022-02-24 17:12
The PrettyGcode patch doesn't fix my problem either. I think this may be a different issue, though. Do you want me to open a separate issue?

**Comment by LazeMSS** [comment] 2022-02-24 17:50
Could you all try without pretty gcode plugin? It has quite a few "hacks" i just think I have fixed some of it now I looked further into it. I don't have any problems when I disable the pretty gcode plugin

**Comment by CBDesignS** [comment] 2022-02-24 17:52
it is removed already along with floating nav bar so I can rule both out.

**Comment by ManuelMcLure** [comment] 2022-02-24 18:25
Removing PrettyGCode has no apparent effect on my problem.

**Comment by CBDesignS** [comment] 2022-02-24 18:40
> > it is removed already along with floating nav bar so I can rule both out.
> 
> And it still freezes after a while?

yes. the 2nd video is with both removed

**Comment by LazeMSS** [comment] 2022-02-24 19:08
The hunt continues...

**Comment by LazeMSS** [comment] 2022-02-25 11:35
@ManuelMcLure  could you open a seperate issue - they are not related.

@CBDesignS  could you try and open the developer console and on the network stream look if the stream stops to increase in size when the stream stops - like this:
![image](https://user-images.githubusercontent.com/69049371/155708578-a9498dbc-22c2-418e-922d-5638444b9fe4.png)

**Comment by CBDesignS** [comment] 2022-02-25 13:59
Is this what you are looking for ? 

![cam9](https://user-images.githubusercontent.com/54717994/155726044-75503f9b-2929-4c4b-9ff5-2a290700563b.jpg)

Video:-
https://1drv.ms/v/s!AisctMQ7h6vWn_MheUwO3mz84EP_Ow?e=dxLZ77

Now I have just noticed. when the stream freezes if I jump to an open tab hang about for a few seconds then jump back to the octo tab the stream sometimes restarts as if the stream is getting an " old school html-1 era on focus refresh command".

![cam10](https://user-images.githubusercontent.com/54717994/155727245-ef9ffa07-e2e8-4e12-ae76-527429d99805.jpg)

A short vid showing the tab swapping i mentioned above.

https://1drv.ms/v/s!AisctMQ7h6vWn_MiiK4l22piT8ZJKg?e=TOSUPN

**Comment by CBDesignS** [comment] 2022-02-25 17:14
Devtools for Micr$oft Edge. this is from freeze - refresh & stream playing - freeze

![cam11](https://user-images.githubusercontent.com/54717994/155757512-ea8a7d21-a267-4447-a7a2-5b92f3f07bbc.jpg)

**Comment by LazeMSS** [comment] 2022-02-25 17:46
Yes the switching to another tab and back is default behaviour in OctoPrint to prevent the stream running when the tab is non visible. But what we are chasing is what's causing the stream to stop.

I will write a short snippet your can insert into the developer console so we can maybe trace what causing the halt of the stream.

Btw does it always happen at the same time and have you tried switching to the temperature tab instead of the control tab and see if it's any different

**Comment by CBDesignS** [comment] 2022-02-25 17:57
it is random as far as I can tell when it will happen and on any octoprint tab. not just the control tab. I am used to clicking on the second tab for pretty g code and must have automatically just clicked like usual hance the reason it was on control.

**Comment by LazeMSS** [comment] 2022-02-25 19:34
Okay I will continue to examine it. I just can't figure out what's triggering the stop of the stream.

**Comment by CBDesignS** [comment] 2022-02-25 20:56
it`s got me double guessing at my computer skills. As this second printer is based on a fresh build of octo on o/s buster I never used it to print anything as it`s my OLD semi retired printer so I have just downgraded back to ui build 0.1.8.1 just to make sure the webcam is actually working as it should and this has not been a wild goose chase for a faulty webcam. Yes the webcam and stream works as it should. 

One thing I have noticed is the stream window on 1.8.1 is slightly smaller than it is in 1.8.7 when it is docked in the right corner and it is a great deal smaller when its floating free. Could freezing be related to the size in some random way.

build 1.8.1
![Inkedcam12_LI](https://user-images.githubusercontent.com/54717994/155801615-99915d14-01d4-4e83-a0fa-31fa9a4c1730.jpg)

Build 1.8.7
![Inkedcam5_LI](https://user-images.githubusercontent.com/54717994/155801247-8139f8eb-e520-412d-9868-5fd0cc349a03.jpg)

**Comment by LazeMSS** [comment] 2022-02-25 22:07
Yes the old version did alot of dirty tricks to try and keep the streams running - the new version is alot more clean but still there should be nothing kill of the stream.

Try running the following in the developer console:

`OctoPrint.coreui.viewmodels.controlViewModel.webcamLoaded.subscribe(function(state) {
    console.log(state)
});
OctoPrint.coreui.viewmodels.controlViewModel.webcamError.subscribe(function(){
console.log('webcam error');
});
`

**Comment by CBDesignS** [comment] 2022-02-26 14:03
I have a slight problem. not sure if it could have been the problem or this is just a poor timed coincidence. the tf card I use on the old printer has just died. humm but the other new Ender 5 Max (mks sgen -L v1) printer showed the same problem so I guess this is just piss poor bad luck with this tf card. it was at least 7 years old. I will rebuild from new card and only install UI and take it from there. back to basics.

**Comment by clarkiej** [comment] 2022-02-27 10:47
I have tested and have the same result with both a Pi 3B+ and a Pi 4 4GB
Tested with a Logitech C310and a 8MP document camera with the same result.
Webcam does not display while camera works fine when testing webcam stream and when turned on under Dashboard:
![image](https://user-images.githubusercontent.com/81622030/155879122-cae86ab8-21a1-437f-8c82-c2e1fc7c61f4.png)
Cam,era passes Stream Test:
![image](https://user-images.githubusercontent.com/81622030/155879200-a33bd819-b80e-4950-81b1-086f7b384b25.png)

Camera works under Camera Settings Plugin:
![image](https://user-images.githubusercontent.com/81622030/155879189-9bfeb753-1ff9-4d5b-8dc6-5f3ad116a94c.png)

No display under Webcam:
![image](https://user-images.githubusercontent.com/81622030/155879100-18af387f-2291-4584-8aca-61ce5954af64.png)

Same result with either Floating Overlay or Full Sdcreen Camera:
![image](https://user-images.githubusercontent.com/81622030/155879272-c4ac2d8d-d77d-47ea-b0ed-b66592b78f37.png)

**Plugins installed**
- Autoscroll[autoscroll] v0.0.3
- Bed Visualizer[bedlevelvisualizer] v1.1.1
- BetterHeaterTimeout[BetterHeaterTimeout] v1.3.0
- Camera Settings[camerasettings] v0.3.1
- Cost Estimation[costestimation] v3.5.0
- Dashboard[dashboard] v1.19.8
- Detailed Progress[detailedprogress] v0.2.7
- DisplayLayerProgress Plugin[DisplayLayerProgress] v1.28.0
- Filament Manager[filamentmanager] v1.9.1
- Navbar Temperature Plugin[navbartemp] v0.14
- Octolapse[octolapse] v0.4.1
- Preheat Button[preheat] v0.8.0
- PrintJobHistory[PrintJobHistory] v1.16.0
- PrintTimeGenius Plugin[PrintTimeGenius] v2.2.8
- Resource Monitor[resource_monitor] v0.3.6
- Smart Preheat[smartpreheat] v0.0.6
- SpoolManager Plugin[SpoolManager] v1.6.1
- **UI Customizer[uicustomizer] v0.1.8.7**
- WebcamTab[webcamtab] v0.2.12


**UI Customizer settings**
- addWebCamZoom: true
- centerTopIcons: true
- compactMenu: true
- compressTempControls: true
- disableTermInactive: false
- filesFullHeight: true
- fixedFooter: true
- fixedHeader: true
- fluidLayout: true
- gcodeFullWidth: false
- hideGraphBackground: true
- hideMainCam: false
- mainTabsCustomize: true
- navbarplugintempfix: true
- responsiveMode: true
- saveAccordions: false
- themeLocal: false


**Software versions**
- OctoPrint 1.7.3
- Python 3.7.3
- OctoPi 0.18.0

**Browser**
- Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0

**Comment by LazeMSS** [comment] 2022-02-27 15:50
@clarkiej try disabling the following plugins:
dashboard and webcam tab.

I'm pretty sure it's related to them. I will check more later

**Comment by clarkiej** [comment] 2022-02-28 02:53
I got teh same result using Float/Fullscreen Webcam . I will try disabling dashboard and webcam tab when my current print finishes and let you know how I get on

**Comment by clarkiej** [comment] 2022-02-28 09:25
I have disabled the webcam tab and now the  UI webcam display is working happily with Dashboard still enabled. I added your Pretty Gcode plugin as well and it is still working fine
![image](https://user-images.githubusercontent.com/81622030/155957133-3fd9a3b8-80dc-4e77-8d9f-2dc78d16df96.png)

If the Float/Fullscreen webcam is set to "float" the webcam works fine in the control section but if you set it to "FullScreen" when yuo swith to teh control section tab the camera sometimes is blank untill you zoom to full screen and back and then the camera seems to work fine:

Set to "Float":
![image](https://user-images.githubusercontent.com/81622030/155957647-2ef5bcb9-eba4-4857-b2d3-25535db798b5.png)

**Comment by ddpt83** [comment] 2022-02-28 14:24
## Description
**ENTER DESCRIPTION HERE
Describe your problem?
I have the same Problem. Maybe this test can help you.
What is the problem?
In same cases, Webcam preview in right part of screen just says Loading webcam until it gives up
Can you recreate it?
Yes. If I reload the page (F5) when the TAB was on "Control TAB", the Webcam is always OK.
If I reload the page when we are on another TAB, the Webcam never does display.
Without reloading, when I click on "Control TAB" the Webcam is displaying again.

Did you try disabling plugins?
I disabled PrettyGcode.
Did you remember to update the subject?**
<hr>

**Plugins installed**
- Bed Visualizer[bedlevelvisualizer] v1.1.1
- Camera Settings[camerasettings] v0.3.1
- Cost Estimation[costestimation] v3.5.0
- Cura Thumbnails[UltimakerFormatPackage] v1.0.1
- DisplayLayerProgress Plugin[DisplayLayerProgress] v1.28.0
- Domoticz[domoticz] v0.1.3
- DryRun Plugin[DryRun] v1.2.0
- Exclude Region[excluderegion] v0.3.0
- Filament Manager[filamentmanager] v1.9.1
- Firmware Updater[firmwareupdater] v1.13.1
- GcodeEditor[GcodeEditor] v0.2.12
- Marlin GCode Documentation[marlingcodedocumentation] v0.16.0
- Octolapse[octolapse] v0.4.1
- Preheat Button[preheat] v0.8.0
- PrintJobHistory[PrintJobHistory] v1.16.0
- Prusa Leveling Guide[PrusaLevelingGuide] v1.0.17
- PSU Control[psucontrol] v1.0.6
- Pushbullet[octobullet] v0.1.14
- Pushover[pushover] v0.3.8
- Resource Monitor[resource_monitor] v0.3.6
- Slicer Thumbnails[prusaslicerthumbnails] v1.0.0
- System Command Editor[systemcommandeditor] v0.3.4
- Terminal Commands Extended[terminalcommandsextended] v0.1.6
- Terminal Messaging[terminalmessaging] v0.1.0
- Translate Model Plugin[translatemodel] v0.2.0
- **UI Customizer[uicustomizer] v0.1.8.7**


**UI Customizer settings**
- addWebCamZoom: true
- centerTopIcons: true
- compactMenu: true
- compressTempControls: false
- disableTermInactive: false
- filesFullHeight: true
- fixedFooter: true
- fixedHeader: true
- fluidLayout: true
- gcodeFullWidth: false
- hideGraphBackground: false
- hideMainCam: true
- mainTabsCustomize: true
- navbarplugintempfix: true
- responsiveMode: true
- saveAccordions: false
- themeLocal: false


**Software versions**
- OctoPrint 1.7.3
- Python 3.7.3
- OctoPi 0.17.0

**Browser**
- Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0

**Comment by DrieStone** [comment] 2022-02-28 18:46
## Description
**ENTER DESCRIPTION HERE

I want to say that I'm having a similar issue. I get "Loading Webcam...." but nothing ever happens. The Webcam tab also doesn't show anything. I can go into the settings and test my webcam and it comes up properly. 

This was working until the recent update.

I've tried restarting everything. I've tried this in both Safari and Chrome on my Mac (same effect).

<hr>

**Plugins installed**
- Access Anywhere - The Spaghetti Detective[thespaghettidetective] v1.8.6
- Arc-Welder[arc_welder] v1.1.0rc4
- Bed Visualizer[bedlevelvisualizer] v1.1.1
- BLTouch Plugin[BLTouch] v0.3.4
- Cancel Objects[cancelobject] v0.4.6
- GcodeEditor[GcodeEditor] v0.2.12
- OctoKlipper[klipper] v0.3.9.4
- Octolapse[octolapse] v0.4.1
- OctoPrint-IFTTT[IFTTT] v1.4.0
- PrintTimeGenius Plugin[PrintTimeGenius] v2.2.8
- Progress Title[progress_title] v0.1.2
- Smart Filament Sensor[smartfilamentsensor] v1.1.6.1
- Smart Preheat[smartpreheat] v0.0.6
- **UI Customizer[uicustomizer] v0.1.8.7**
- WebcamTab[webcamtab] v0.2.12


**UI Customizer settings**
- addWebCamZoom: true
- centerTopIcons: true
- compactMenu: true
- compressTempControls: true
- disableTermInactive: false
- filesFullHeight: true
- fixedFooter: true
- fixedHeader: true
- fluidLayout: true
- gcodeFullWidth: false
- hideGraphBackground: true
- hideMainCam: true
- mainTabsCustomize: true
- navbarplugintempfix: true
- responsiveMode: true
- saveAccordions: true
- themeLocal: false


**Software versions**
- OctoPrint 1.7.2
- Python 3.7.3
- OctoPi 0.17.0

**Browser**
- Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15

**Comment by LazeMSS** [comment] 2022-02-28 21:37
If you are running webcam tab that's a problem. Im looking into that right now

**Comment by DrieStone** [comment] 2022-02-28 21:40
It happens even when I hide the tab.

![Screen Shot 2022-02-28 at 4 39 30 PM](https://user-images.githubusercontent.com/230261/156063112-23295841-536c-4a14-a39e-a722b2474466.png)

**Comment by LazeMSS** [comment] 2022-02-28 21:49
There should not be anything breaking the stream from loading when webcam tab has been disabled.

I will look into it tomorrow

**Comment by CBDesignS** [comment] 2022-02-28 21:58
@LazeMSS  After the tf card giving up the ghost on me I have just clean installed the curent octo on a new tf card and UIC is the only plugin installed apart from the pre installed ones and so far this test print it has not frozen the stream. If this works I can start installing plugins one at a time until I break it. well thats the plan. I have forgot just how sparse octo is in its generic form.. My cam stream would have frozen less than 60 seconds into a print and its going strong at 5 mins in.

**Comment by ManuelMcLure** [comment] 2022-03-01 01:27
Entered new issue #238 for the issue I reported. It looks like an interaction with PrintJobHistory.

**Comment by DrieStone** [comment] 2022-03-01 02:45
> There should not be anything breaking the stream from loading when webcam tab has been disabled.
> 
> I will look into it tomorrow

I figured it out. In my case I had the "webcam tab" plugin active. Once I disabled the plugin, it started to work.

**Comment by CBDesignS** [comment] 2022-03-01 12:27
@LazeMSS So far in I have just installed prettygcode and as you already knew it only causes the double stream window on the right or wherever it is configured but it does not cause the stream freezing. I will try your patched version of pretty gcode and see if that fixes the double stream window. If not hey hoy I will move on to the next plugin while trying to freeze the stream.

**Comment by LazeMSS** [comment] 2022-03-01 16:05
@clarkiej and @ddpt83 your problems are probally related to PrintJobHistory creating a duplicate of the main webcam id:
https://github.com/OllisGit/OctoPrint-PrintJobHistory/issues/194

**Comment by ddpt83** [comment] 2022-03-01 17:46
After disabling PrintJobHistory, the webcam is displayed correctly.

**Comment by CBDesignS** [comment] 2022-03-01 18:24
@LazeMSS I dont know if I am getting closer or further away..  Anyway here is the list of plugins I have instralled one at a time and tested with a full reboot after every install and a test print of a part.. 

**Plugins installed**
- Active Filters Extended[active_filters_extended] v0.1.0
- Arc-Welder[arc_welder] v1.1.0rc4
- Marlin EEPROM Editor[eeprom_marlin] v3.2.0
- PrettyGCode[prettygcode] v1.2.4                                      <-- your fixed version
- Slicer Thumbnails[prusaslicerthumbnails] v1.0.0
- **UI Customizer[uicustomizer] v0.1.8.7**
- WS281x LED Status[ws281x_led_status] v0.8.0

**Comment by LazeMSS** [comment] 2022-03-01 18:25
@CBDesignS  and it still works?

**Comment by CBDesignS** [comment] 2022-03-01 18:26
> @CBDesignS and it still works?

yea. still going strong.

**Comment by clarkiej** [comment] 2022-03-02 00:45
> @clarkiej and @ddpt83 your problems are probally related to PrintJobHistory creating a duplicate of the main webcam id: [OllisGit/OctoPrint-PrintJobHistory#194](https://github.com/OllisGit/OctoPrint-PrintJobHistory/issues/194)

After disabling PrintJobHistory floating webcam still works fine but FullScreenWebcam when you click on full screen does not work still. THis is teh same result with or without PrintJobHistory enabled

**Comment by clarkiej** [comment] 2022-03-02 10:14
With PrintJobHistory enabled or disabled, the FloatingWebcam option works fine. You can move the window around when you click on the zoom icon in the top right corner. If you select FullScreenWebcam, the webcam shows, but when you click on teh zoom icon in teh top right corner, the webcam view vanishes and does not reappear.

Sorry for all teh comments as we know you are trying to identify teh issue.

**Comment by LazeMSS** [comment] 2022-03-02 12:47
> With PrintJobHistory enabled or disabled, the FloatingWebcam option works fine. You can move the window around when you click on the zoom icon in the top right corner. If you select FullScreenWebcam, the webcam shows, but when you click on teh zoom icon in teh top right corner, the webcam view vanishes and does not reappear.
> 
> Sorry for all teh comments as we know you are trying to identify teh issue.

Same options and plugins as posted here: https://github.com/LazeMSS/OctoPrint-UICustomizer/issues/234#issuecomment-1053486556

I can't recreate that - I have a fix for most of the stuff we have found so far

**Comment by CBDesignS** [comment] 2022-03-02 13:17
@LazeMSS Another day and another session trying to freeze the stream

everything is still working as it should and the list is getting smaller.

BLTouch Plugin[BLTouch] v0.3.4
Camera Settings[camerasettings] v0.3.1
FileManager[filemanager] v0.1.6
Firmware Updater[firmwareupdater] v1.13.1
LightsOut[lightsout] v0.1.2
Navbar Temperature Plugin[navbartemp] v0.14
PrintTimeGenius Plugin[PrintTimeGenius] v2.2.8

from looking at the list of plugings left to install Lightsout, BLtouch & firmware updater I would say will be ok but the rest all would seem to indicate they interact with the octo gui / ui so could it be 

Camera Settings[camerasettings] v0.3.1
FileManager[filemanager] v0.1.6
Navbar Temperature Plugin[navbartemp] v0.14
PrintTimeGenius Plugin[PrintTimeGenius] v2.2.8

If and I hope it is a big if these all reinstall and the stream still works as it should the only other thing I can think could be.. before your UIC plugin made life easy to skin and arrange the oct window I had a heavily modded ui using the good old hacks by using f12 dev mode to find and change settings and maybe even tho the relevant plugins were removed maybe some settings were left in a config or some other file and that is causing the problems. this sprung to mind because my other printer shows the same problems and I cheated when I set octo on its pi, I just used a backup from the old machine (pre built and ready to go) and only required minimal setup time to get me printing. 

Because this is a clean from scratch setup whatever file or setting that may have caused this will not exist so uic is working correctly as it should .

this was just a though that passed thru my foggy mind lastnight
Sirhc

**Comment by CBDesignS** [comment] 2022-03-02 16:56
@LazeMSS 

2 plugins left 

Camera Settings[camerasettings] v0.3.1
FileManager[filemanager] v0.1.6

I never used Filemanager even tho it was installed and camera settings did nothing for the basic as they come 640x480 scabby webcam that I use on this printer.  I will install them with the hope that one of these last 2 will break the stream.. 

Its not looking good for blaming one or more of the plugins so back to the other though of old settings/corrupt dom data etc as the likley cause of the stream freezing. I know most users of octo are like most users of every other electronic device, they see an app or plugin or are told about one and they have to go install it, mess about with it unknowingly changing things, then remove it or just leave it installed but not using it and a little later on things start to go wrong and because there has been that much done on the system no one will even know where to start trying to fix it.. ( I was in IT for 30 years and have seen it day in and out with boot looping computers and phone apps that refuse to start)..

**Comment by LazeMSS** [comment] 2022-03-02 17:39
I will try and make a branch for testing this ASAP

**Comment by LazeMSS** [comment] 2022-03-03 13:01
Try installing the webcam test branch by using: https://github.com/LazeMSS/OctoPrint-UICustomizer/archive/refs/heads/webcamprobs.zip

Guide: https://plugins.octoprint.org/help/installation/

**Comment by CBDesignS** [comment] 2022-03-03 13:45
your patch in action..

![cam20](https://user-images.githubusercontent.com/54717994/156576542-c4ae83a6-a591-4cad-b53c-4dde38ad924f.jpg)

before the patch (on this setup) the webcam froze or was missing and today it was missing untill I applied your patch and the webcam popped back up so. will full reboot and see how it goes.. Fingers crossed @LazeMSS

**Comment by clarkiej** [comment] 2022-03-03 19:26
Patch has been applied.With the patch both floating and fullscreen webcam appear to work. On startup after applying the patch the message regarding PrettyGcode still popped up but I have your modified version running without incident.

Webcam enabled in Dashboard and Webcam mode set to Fullscreen
![image](https://user-images.githubusercontent.com/81622030/156637638-7723f349-f32f-4a5c-83cf-31f1b8013b7f.png)
Triggering FullScreen works fine:
![image](https://user-images.githubusercontent.com/81622030/156637743-5409a177-763b-4dd9-a65e-26448e695485.png)

When set to Overlayfloating Mode Triggering also works without incident:
![image](https://user-images.githubusercontent.com/81622030/156637998-60419142-76ac-4a42-a397-6f53850c026a.png)

The webcam image also loaded immediately on connecting to OctoPrint as well when previously there was a lag and a spinning wheel before loading roughly half teh time.

**Comment by LazeMSS** [comment] 2022-03-04 12:38
Thanks for all the feedback!

regarding the "notice/warning" about other plugins - its just there so I can remeber and easier "turn down" bug reports - and maybe nudge the other developers to fix their bugs ;)

**Comment by LazeMSS** [comment] 2022-03-05 08:54
Should be fixed in https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.8.9
if not then please reopen this issue.

**Closed by LazeMSS** 2022-03-05 08:54 UTC
Labels: bug, done
