### ISSUE TITLE
Everything is gone by help of activating "Suppress processing responses"

### ISSUE THREAD

**Issue by Charly333** [LazeMSS/OctoPrint-UICustomizer#7] opened 2020-12-01 17:07 UTC
After activating "Suppress processing responses" in Terminal Window only footer line and some informations in Top bar are there, the rest is gone. Most of the tabs for the three columns in Plugin setup are gone to. The two remaining "Main tabs" and "Webcame" can be moved araound without any impact. Octoprint screen keeps empty.

**Comment by LazeMSS** [comment] 2020-12-02 06:15
I can't replicate this error in any way - do you have any other plugins installed?

**Comment by LazeMSS** [comment] 2020-12-02 13:56
Duplicate of #9 
Is my best guess - closing - please reopen if not fixed in the next release

**Closed by LazeMSS** 2020-12-02 13:56 UTC
Labels: duplicate
