### ISSUE TITLE
[BUG] Compatibility issue with OctoPrint 1.9 - webcam not working

### ISSUE THREAD

**Issue by giuliolibrando** [LazeMSS/OctoPrint-UICustomizer#281] opened 2023-03-08 11:04 UTC
**Describe the bug**

OctoPrint 1.9rc2  has moved Webcam integration to a plugin interface.
[https://octoprint.org/blog/2023/03/07/new-release-candidate-1.9.0rc1/](Release info)

Webcam View is not working, keep showing "Webcam stream loading..".
![image](https://user-images.githubusercontent.com/76574961/223695816-bd5f6189-a198-4124-9f51-0395955b3fca.png)

It works without the UI Customizer plugin.

**Comment by NewsGuyTor** [comment] 2023-03-08 22:22
Please don't remove the webcam functionality, it is vital for so many people! If the worst come to worst, and it is s too much work, please implement the simple workaround I detail here:

1. <img width="1162" alt="Skjermbilde 2023-03-08 kl  22 45 44" src="https://user-images.githubusercontent.com/19603024/223858512-64ded676-3206-41fd-b2d3-bdc779a44ad7.png">

2. <img width="1162" alt="Skjermbilde 2023-03-08 kl  22 47 03" src="https://user-images.githubusercontent.com/19603024/223858509-bfe9916d-706c-4e91-a20c-47615f7703c1.png">

3. <img width="1162" alt="Skjermbilde 2023-03-08 kl  22 49 23" src="https://user-images.githubusercontent.com/19603024/223858487-4b9911a6-b04a-47f2-bccb-2636701ea7e6.png">

Replacing the HTML with the image HTML is a great workaround at least, a way better option that removing the webcam functionality.

**Comment by LazeMSS** [comment] 2023-03-09 08:02
@NewsGuyTor its not that easy but I have already fixed it in dev I hope

**Comment by CornFlakes1991** [comment] 2023-03-09 23:05
Even after updating to this fix, this issue persists

**Comment by jneilliii** [comment] 2023-03-09 23:37
@CornFlakes1991 is it the same error relative to "subscribe" as in the original error post in your browser's developer tools console tab?

**Comment by jneilliii** [comment] 2023-03-09 23:51
I suspect this may be a race condition or something. I just checked and this is the error I see in console tab with the latest version. However, if I run the command that is being assigned to OrgTabChange it is a function. 

![image](https://user-images.githubusercontent.com/5249455/224187113-ca655be0-e9ba-41e8-9976-753f6636842e.png)

**Comment by CornFlakes1991** [comment] 2023-03-10 11:37
> 

![3x7nsB](https://user-images.githubusercontent.com/26132979/224306460-544a69e2-2615-45d9-b736-a5a2a8759fd4.png)

**Comment by LazeMSS** [comment] 2023-03-10 11:40
@CornFlakes1991 on RC2 or normal?

**Comment by jneilliii** [comment] 2023-03-10 12:49
Looks like 1.9.0 based on friendship warning. Error is prettygcode, disable that plugin and check again.

**Comment by CornFlakes1991** [comment] 2023-03-10 14:16
> @CornFlakes1991 on RC2 or normal?

RC2



> Looks like 1.9.0 based on friendship warning. Error is prettygcode, disable that plugin and check again.

Disabled it and still not webcam image :/

**Comment by jneilliii** [comment] 2023-03-10 15:28
Yes, this was what I was seeing too with the patched files. There's still something missing relative to keeping the stream live when not on the control tab. I'll be looking at this over the weekend for all my impacted plugins and will have a better idea of how the new classic webcam plugin is controlling this.

**Comment by jneilliii** [comment] 2023-03-10 15:29
maybe we could ask @crysxd what is needed to keep the stream active...

**Comment by crysxd** [comment] 2023-03-10 15:47
The problem is that you can now have more than one webcam and OctoPrint has a drop down to select the shown webcam. The controls VM will stop the webcam stream of inactive webcams, similarly to when you move away from the OctoPrint tab in your browser. The corresponding code is here:

- https://github.com/OctoPrint/OctoPrint/blob/95e87eb1970d8e322738f9698c9d665d78f2d74e/src/octoprint/static/js/app/viewmodels/control.js#L58
- https://github.com/OctoPrint/OctoPrint/blob/95e87eb1970d8e322738f9698c9d665d78f2d74e/src/octoprint/static/js/app/viewmodels/control.js#L84
- https://github.com/OctoPrint/OctoPrint/blob/95e87eb1970d8e322738f9698c9d665d78f2d74e/src/octoprint/static/js/app/viewmodels/control.js#L109

**Comment by fly74** [comment] 2023-03-16 19:52
The other thing is that the option "Hide webcamera on Control tab" don't hide it in OP 1.9.0rc2.

**Comment by LazeMSS** [comment] 2023-03-17 16:46
@fly74 did you turn on the webcam widget?

**Comment by fly74** [comment] 2023-03-17 18:42
@LazeMSS What do mean?

It is emty in the Main view:

![Screenshot 2023-03-17 193901](https://user-images.githubusercontent.com/38754941/225990950-dc6b00cd-e1c5-46b2-94f7-2057cea8d2a4.JPG)

And shown in the control section, even if hide option is set:

![Screenshot 2023-03-17 193919](https://user-images.githubusercontent.com/38754941/225991149-7a154dbb-b81a-4e1f-85fa-92bfd5499c95.JPG)

Enabled here?:

![Screenshot 2023-03-17 194021](https://user-images.githubusercontent.com/38754941/225991204-86995fb0-2110-4183-a1f3-4dec7ed2c4e0.JPG)

**Comment by LazeMSS** [comment] 2023-03-17 22:32
@fly74  on the RC2 or normal 1.8.2 octoprint?

**Comment by fly74** [comment] 2023-03-18 06:30
> @fly74  on the RC2 or normal 1.8.2 octoprint?
> 
> 

In the rc2. When I rollback to 1.8.2 everything is fine.

**Comment by LazeMSS** [comment] 2023-03-18 08:10
Ohh i might have that fixed in the upcoming release but that requires the rc3 to be released first

**Closed** 2023-03-22 20:42 UTC
Labels: bug, done

**Comment by fly74** [comment] 2023-03-22 20:46
@LazeMSS I can confirm, it works now. thx.

**Comment by abulka** [comment] 2023-04-05 23:54
> This should now be fixed when 1.9.0 is released - closing for now - wait for 1.9.0 release or try the RC3 version. https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.9.4

Can this RC be installed via the plugin manager? My plugin manager is not listing plugins at the moment for some reason - so I can't see if RC are also listed in OctoPrint's plugin manager.  Can I install the new RC version of UICustomizer via pip perhaps?

I am running `OctoPrint: 1.8.7` and the layout is a bit messed up.  Currently OctoPrint's pip lists

    UI-Customizer             0.1.9.4

**Comment by crysxd** [comment] 2023-04-06 00:33
@abulka If you are not using OctoPrint 1.9 then this is not your issue. If you want to use OctoPrint 1.9 RC, you can select it in the "Software Update" settings (select "Maintenance RC"), but this might bring you more issues than it solves

<img width="564" alt="Screenshot 2023-04-06 at 07 32 54" src="https://user-images.githubusercontent.com/5859228/230243313-d92c2eee-cb00-4658-8e14-f043ff66a7ea.png">

**Comment by abulka** [comment] 2023-04-06 00:43
I rebooted my pi and the plugin manager started working again. And the layout corrected itself. So all good. And I'll stay away from OctoPrint 1.9 RC till its stable etc - thanks.

**Comment by WimVDK** [comment] 2023-08-27 18:19
Still broken on Octoprint 1.9.2 and UI Customizer 0.1.9.8

**Comment by LazeMSS** [comment] 2023-08-27 22:03
@WimVDK could you explain a bit more?

**Comment by LazeMSS** [comment] 2023-08-28 19:40
@WimVDK  try disabling A dashboard for Octoprint or maybe just their webcam implantation

**Comment by WimVDK** [comment] 2023-08-28 19:56
I explicitly installed that one just to get a working webcam feed again on the home page. If this bug gets fixed I'm uninstalling it again probably. It's UI-Customizers that's not not working

**Comment by jneilliii** [comment] 2023-08-28 20:08
I still think it might be my plugin, consolidate temp control.

**Comment by WimVDK** [comment] 2023-08-28 20:12
Going to bed now. I'll see if i can confirm ly earlier statement about CTC or UIC. To be continued

**Comment by WimVDK** [comment] 2023-08-29 16:11
> I still think it might be my plugin, consolidate temp control.

I have to correct my earlier statement CTC is indeed the culprit. The moment that one was disabled and octoprint was disabled preview worked fine on all tabs. So how do we go from here?

**Comment by jneilliii** [comment] 2023-08-29 16:44
Try switching to consolidated tabs plugin instead of that one, combine temperature and control and see if it's still an issue.

**Comment by WimVDK** [comment] 2023-08-29 17:11
That one works. I'll have to tinker around with it to see which method i like best. Certainly a neat concept though! How do you remove "enabled" tabs? couldn't find that in the configuration instructions on the github/plugin settings. Seems like the "spoolmanager plugin","State","Files", "connection" and "webcam" sections can't be moved either (yet)

**Comment by jneilliii** [comment] 2023-08-29 20:35
That plugin only works on combining tabs, not sidebar items.
