### ISSUE TITLE
Missing tabs in new functionality.

### ISSUE THREAD

**Issue by LMS0815** [LazeMSS/OctoPrint-UICustomizer#21] opened 2020-12-09 17:29 UTC
Several/All (plugin) Tabs are missing at your tab management window (e.g. bedlevelvisualizer, resource_monitor, arc_welder, smartpreheat).
![image](https://user-images.githubusercontent.com/8235214/101663783-65371900-3a4b-11eb-9819-3933621dd2a1.png)

Please consider adding an option at icon position in the tab (left/right) to hide lable.
There is no need to have a label if you choose a proper icon :)

**Plugins installed:**
- M117PopUp
- action_command_notification
- action_command_prompt
- announcements
- arc_welder
- backup
- bedlevelvisualizer
- discovery
- errortracking
- firmwareupdater
- m73progress
- pi_support
- pluginmanager
- resource_monitor
- smartpreheat
- softwareupdate
- taborder
- tracking
- uicustomizer

**Software versions:**
- OctoPrint 1.5.1
- Python 3.7.3
- OctoPi 0.18.0

**Comment by LazeMSS** [comment] 2020-12-09 18:54
Duplicate of #19  - the requested new feature is in next release

**Closed by LazeMSS** 2020-12-09 18:54 UTC
Labels: duplicate

**Comment by LMS0815** [comment] 2020-12-10 11:53
Thank you.
