### ISSUE TITLE
add option to merge tabs and control the temperature

### ISSUE THREAD

**Issue by ssavickiy** [LazeMSS/OctoPrint-UICustomizer#45] opened 2020-12-25 19:14 UTC
It will be very convenient if you can combine the temperature chart and buttons with the tab control

**Comment by LazeMSS** [comment] 2020-12-26 12:03
Duplicate of: https://github.com/LazeMSS/OctoPrint-UICustomizer/issues/30

**Closed by LazeMSS** 2020-12-26 12:03 UTC
