### ISSUE TITLE
UI Costumizer UI gone bug with remove temp background

### ISSUE THREAD

**Issue by JRosello** [LazeMSS/OctoPrint-UICustomizer#50] opened 2021-01-02 10:07 UTC
## Description
Describe your problem?
Marked the option to hide temp background
What is the problem?
All UI is gone except top and low bars
Can you recreate it?
Yes
Did you try disabling plugins?
If you disables de plugin normal UI works, as soon you reenable the plugin UI is gone 
Did you remember to update the subject?**
<hr>

**Plugins installed**
- FileManager[filemanager] v0.1.4
- Fullscreen Plugin[fullscreen] v0.0.6
- Marlin GCode Documentation[marlingcodedocumentation] v0.11.0
- Navbar Temperature Plugin[navbartemp] v0.14
- Octolapse[octolapse] v0.4.1
- PrintJobHistory[PrintJobHistory] v1.10.0
**- **UI Customizer[uicustomizer] v0.1.2.0****

**UI Customizer settings**
- addWebCamZoom: true
- centerTopIcons: true
- compactMenu: true
- disableTermInactive: false
- fixedFooter: true
- fixedHeader: true
- fluidLayout: true
- gcodeFullWidth: false
- hideGraphBackground: false
- hideMainCam: false
- mainTabsCustomize: true
- navbarplugintempfix: false
- responsiveMode: true

**Software versions**
- OctoPrint 1.5.2
- Python 3.7.3
- OctoPi 0.17.0

**Browser**
- Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:84.0) Gecko/20100101 Firefox/84.0

**Comment by LazeMSS** [comment] 2021-01-02 11:01
This is a duplicate of another bug I have - this is really strange - have you fixed it? Or is there anyway I can have a look at your screen/teamviewer etc. to try and look into what happening?

**Comment by LazeMSS** [comment] 2021-01-02 15:28
Or could you post the output of your developer console?

**Comment by seebaer1976** [comment] 2021-01-02 15:45
have the same problem.
with update to 0.1.2.0 - Fixed 0.1.1.9 release, everything is gone except for the header and footer.
see image:

![Bildschirmfoto 2021-01-02 um 16 35 24](https://user-images.githubusercontent.com/11788213/103460835-c041f000-4d19-11eb-9d17-ab0396c94591.png)


**Plugins installed**
- Bed Visualizer[bedlevelvisualizer] v1.0.0
- Cancel Objects[cancelobject] v0.4.4
- Dashboard[dashboard] v1.16.3
- DisplayLayerProgress Plugin[DisplayLayerProgress] v1.24.0
- Navbar Temperature Plugin[navbartemp] v0.14
- OctoKlipper[klipper] v0.3.2
- PrettyGCode[prettygcode] v1.2.4
- PrintTimeGenius Plugin[PrintTimeGenius] v2.2.7
- PrusaSlicer Thumbnails[prusaslicerthumbnails] v0.1.3
- Themeify[themeify] v1.2.2
- Tuya Smartplug[tuyasmartplug] v0.3.0
- **UI Customizer[uicustomizer] v0.1.2.0**


**UI Customizer settings**
- addWebCamZoom: false
- centerTopIcons: true
- compactMenu: true
- disableTermInactive: false
- fixedFooter: true
- fixedHeader: true
- fluidLayout: true
- gcodeFullWidth: false
- hideGraphBackground: true
- hideMainCam: true
- mainTabsCustomize: true
- navbarplugintempfix: true
- responsiveMode: false


**Software versions**
- OctoPrint 1.5.2
- Python 3.7.3

**Browser**
- Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:84.0) Gecko/20100101 Firefox/84.0

**Comment by LazeMSS** [comment] 2021-01-02 15:56
Could you post output from developer console ?

**Comment by LazeMSS** [comment] 2021-01-02 16:40
I would really like to see if it can be recreated after installing the new version of my plugin - it should not be possible.

**Comment by seebaer1976** [comment] 2021-01-02 16:53
> Could you post output from developer console ?

stupid question. where is find again?

**Comment by seebaer1976** [comment] 2021-01-02 16:57
can you use them?

[octoprint.log](https://github.com/LazeMSS/OctoPrint-UICustomizer/files/5760551/octoprint.log)
[plugintimings.log](https://github.com/LazeMSS/OctoPrint-UICustomizer/files/5760552/plugintimings.log)

**Comment by LazeMSS** [comment] 2021-01-02 17:00
I wanted the output of: https://developer.mozilla.org/en-US/docs/Tools/Web_Console#Opening_the_Web_Console

**Comment by LazeMSS** [comment] 2021-01-02 17:01
https://developer.mozilla.org/en-US/docs/Tools/Browser_Console

**Comment by seebaer1976** [comment] 2021-01-02 17:20
here the output of the console:

[console-export-2021-1-2_18-18-16.txt](https://github.com/LazeMSS/OctoPrint-UICustomizer/files/5760589/console-export-2021-1-2_18-18-16.txt)

**Comment by JRosello** [comment] 2021-01-02 19:13
Just for a clue.. if you clean the data on the plugin, re-enable and restart octorpint it works again

**Comment by LazeMSS** [comment] 2021-01-02 20:49
@JRosello but can you make it break again then?

**Comment by JRosello** [comment] 2021-01-02 21:06
Now Seems fine...
I think the problem came when you install the Consolidated Tabs with **UI C**ustomizer plug-in when it is installed and adjusted to your own needs.
I tried uninstalling Consolidated Tabs, clear the **UIC** data, setup **UIC** and the reinstall Consolidated Tabs... now seems that is working.

**Comment by LazeMSS** [comment] 2021-01-02 21:12
Ahh but you did not list Consolidated tabs in the report?

**Comment by JRosello** [comment] 2021-01-02 21:18
Sorry my mistake, when UIC failed Consolidated tabs wasn't installed yet

**Comment by LazeMSS** [comment] 2021-01-02 21:19
Okay - I have a new version out - Im still unable to recreate it but now I can check for the error at least

**Comment by JRosello** [comment] 2021-01-02 21:20
Great thanks!!

**Comment by LazeMSS** [comment] 2021-01-02 21:50
Please try again :)

**Comment by JRosello** [comment] 2021-01-03 08:12
Well tried and now seems to work... I'll reinstall Consolidated Tabs and see how it goes... If NO news Good news

Thanks for your work!!

**Comment by LazeMSS** [comment] 2021-01-03 08:31
I will close for now

**Closed by LazeMSS** 2021-01-03 08:31 UTC
