### ISSUE TITLE
Custom Color in Theme

### ISSUE THREAD

**Issue by tcon2010** [LazeMSS/OctoPrint-UICustomizer#264] opened 2022-09-27 01:01 UTC
I'm using the discoranged theme and simply wanted to change the orange to a new color. I looked at the inspector and saw that it was using --accent from the root of the css. Knowing that, I went to advanced and entered 
`:root {--accent: #aaf0d1 !important;}`
but that did not work upon saving and refreshing. I went back to advanced and just to see what would happen I checked preview and _it worked_. I clicked save and all was good... until I refreshed the page. It went right back to the orange. Is there a simple way of changing colors in the theme as this doesn't seem to be working?

![OctoPrint1](https://user-images.githubusercontent.com/114452845/192406979-172a674c-aeb4-4f56-a077-b62e11689270.JPG)
![OctoPrint2](https://user-images.githubusercontent.com/114452845/192406990-e7e28eb7-a4fb-4d71-89f0-07281b067ff2.JPG)

_**NOTE**_: _I just tried to change the file name color from the dark green to the same custom color I have above. Same results: does not work upon save but does work in preview._

**Comment by LazeMSS** [comment] 2022-09-27 08:20
Its basically because the order of the CSS is handled - I will look into a workaround but Im currently on a break. But the planned feature is to allow customizing the colors in the themes instead of the CSS overwrites

**Comment by j-snijder** [comment] 2022-11-17 11:07
Hi, maybe a tip for use in the meanwhile.

Although octoprint warns you for conflicting plugins you could reinstall Themify ( I did :) ) and use thast together with UIcustomizer.

In my case it worked and I got back the things I altered in Themify (which I was using before I discovered UIcustomizer was preferred bij the Dev.

**Comment by stayingarmed** [comment] 2022-12-11 23:54
Did anything more come of this? I would really like to customize theme colors!

**Comment by LazeMSS** [comment] 2022-12-12 06:45
I just did a full rework of the bugs and features list on another plugin. This week I will go through the UI customizer backlog

**Comment by LazeMSS** [comment] 2022-12-28 20:20
I just started working on the bug backlog - this appears to be as stated by @tcon2010 by using important - even after reloading.
I'm still planning on making an easier customizing where one can specify the color variables

**Comment by LazeMSS** [comment] 2022-12-29 17:54
Closing this as it is working as intended - I will improve it better when "color variables" are customizable

**Closed by LazeMSS** 2022-12-29 17:54 UTC

**Comment by LazeMSS** [comment] 2022-12-29 17:56
https://github.com/LazeMSS/OctoPrint-UICustomizer/issues/217
