### ISSUE TITLE
Gcode viewer should full the entire screen but not the full height :)

### ISSUE THREAD

**Issue by GigaTech** [LazeMSS/OctoPrint-UICustomizer#72] opened 2021-01-24 14:44 UTC
Hi, brilliant plugin.

I have an issue, where the GCode Viewer is NOT filling the full width of the column

![image](https://user-images.githubusercontent.com/3658357/105633735-3d144580-5e52-11eb-896c-63062a2eb36f.png)

in the image, this is a small part in the center of the print bed.

the same issue exists in both Chrome and FireFox

Many Thanks.

**Comment by LazeMSS** [comment] 2021-01-24 15:18
It's strange I have had reports of this before. I will look ASAP

**Comment by GigaTech** [comment] 2021-01-24 16:00
my system info, if needed:

```
browser.user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
connectivity.connection_check: 8.8.8.8:53
connectivity.connection_ok: true
connectivity.enabled: true
connectivity.online: true
connectivity.resolution_check: octoprint.org
connectivity.resolution_ok: true
env.hardware.cores: 4
env.hardware.freq: 1200
env.hardware.ram: 917016576
env.os.bits: 32
env.os.id: linux
env.os.platform: linux2
env.plugins.pi_support.model: Raspberry Pi 3 Model B Rev 1.2
env.plugins.pi_support.octopi_version: 0.17.0
env.plugins.pi_support.throttle_state: 0x0
env.python.pip: 19.3.1
env.python.version: 2.7.16
env.python.virtualenv: true
octoprint.safe_mode: false
octoprint.version: 1.5.3
printer.firmware: Marlin 1.1.8 (Github)
```

Thanks

**Comment by LazeMSS** [comment] 2021-01-24 17:52
Do you have the " Cancel Object Plugin" installed?
Have a look here: https://github.com/LazeMSS/OctoPrint-UICustomizer/issues/43

**Comment by LazeMSS** [comment] 2021-01-24 19:34
Ahh can see from your screenshot now that you dont have the cancel object plugin - can you try and pres F12 and chrome and run this command:
$('#gcode_canvas').prop('class')

And post back what it returns

**Comment by GigaTech** [comment] 2021-01-24 19:40
Hi, no I do not have that plugin installed

![image](https://user-images.githubusercontent.com/3658357/105641459-ff2c1700-5e7b-11eb-900b-125a3eaea60c.png)

it return ""

**Comment by LazeMSS** [comment] 2021-01-24 19:50
Are your sure you are running the latest version of my plugin?

**Comment by GigaTech** [comment] 2021-01-24 19:52
installed today from the plugin manager...

![image](https://user-images.githubusercontent.com/3658357/105641754-ae1d2280-5e7d-11eb-9033-0d42dd46dd91.png)

**Comment by LazeMSS** [comment] 2021-01-24 23:14
Can you try and push the "report a bug" button in my plugin and just dont create the bug report but just copy the text over into this issue. Im looking for which options you have enabled but there should nothing holding it back. 

Can you maybe also try disabling themeify?

**Comment by GigaTech** [comment] 2021-01-24 23:46
## Description
**ENTER DESCRIPTION HERE
Describe your problem?
What is the problem?
Can you recreate it?
Did you try disabling plugins?
Did you remember to update the subject?**
<hr>

**Plugins installed**
- Z Probe Offset[z_probe_offset] v0.5
- Themeify[themeify] v1.2.2
- **UI Customizer[uicustomizer] v0.1.2.5**

**UI Customizer settings**
- addWebCamZoom: true
- centerTopIcons: true
- compactMenu: true
- compressTempControls: true
- disableTermInactive: false
- fixedFooter: false
- fixedHeader: false
- fluidLayout: true
- gcodeFullWidth: false
- hideGraphBackground: true
- hideMainCam: false
- mainTabsCustomize: true
- navbarplugintempfix: true
- responsiveMode: true

**Software versions**
- OctoPrint 1.5.3
- Python 2.7.16
- OctoPi 0.17.0

**Browser**
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36

**Comment by GigaTech** [comment] 2021-01-24 23:59
themeify disabled... the same

![image](https://user-images.githubusercontent.com/3658357/105647816-01a06800-5ea0-11eb-8a08-71319e24c21d.png)

## Description
**ENTER DESCRIPTION HERE
Describe your problem?
What is the problem?
Can you recreate it?
Did you try disabling plugins?
Did you remember to update the subject?**
<hr>

**Plugins installed**
- Z Probe Offset[z_probe_offset] v0.5
- **UI Customizer[uicustomizer] v0.1.2.5**


**UI Customizer settings**
- addWebCamZoom: true
- centerTopIcons: true
- compactMenu: true
- compressTempControls: true
- disableTermInactive: false
- fixedFooter: false
- fixedHeader: false
- fluidLayout: true
- gcodeFullWidth: false
- hideGraphBackground: true
- hideMainCam: false
- mainTabsCustomize: true
- navbarplugintempfix: true
- responsiveMode: true


**Software versions**
- OctoPrint 1.5.3
- Python 2.7.16
- OctoPi 0.17.0

**Browser**
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36

**Comment by LazeMSS** [comment] 2021-01-25 06:57
You need to enable the feature:
![image](https://user-images.githubusercontent.com/69049371/105671423-fc184180-5ee2-11eb-837f-3b96230fda40.png)

Closing

**Comment by GigaTech** [comment] 2021-01-25 12:04
Hi, Thanks for the info.

I left this box unticked as it creates a very long page and jumps to the top of the box then the mouse goes into the preview box, it is unusable in this state.

below is the full window screenshot

![image](https://user-images.githubusercontent.com/3658357/105703529-49a5a600-5f05-11eb-93d3-259384329963.png)

**Comment by LazeMSS** [comment] 2021-01-25 19:02
Well thats the behaviour of the current way of making it full size - the display has to be a square - it might look into some hacks but there are a lot of stuff going onside in the gcode viewer

**Comment by GigaTech** [comment] 2021-01-25 19:32
OK Thanks.

I was assuming that it would look like your images on your front page, such are the 'floating webcam' image / Temperature page

...I just changed the width and it looks OK (with the checkbox "Gcode full-size" unchecked), but then obviously there is more to it than this.

`<canvas id="gcode_canvas"...`

![image](https://user-images.githubusercontent.com/3658357/105754735-54caf700-5f42-11eb-834e-9b8b9532ca8b.png)

Thanks for your time, I am looking forward to an update.
Many Thanks

**Comment by LazeMSS** [comment] 2021-01-25 19:55
Well it looks like that on certain screen resolution due to the aspect ratios

The problem is aspect ratios - the screen get to tall - and some users like that and other don't - so I added it and option and it works like this for the moment.

**Comment by LazeMSS** [comment] 2021-01-25 21:00
I will close for now - I have a better feature planned... :)

**Closed by LazeMSS** 2021-01-25 21:00 UTC
Labels: enhancement
