### ISSUE TITLE
Themify plugin detection error

### ISSUE THREAD

**Issue by Allan-N** [LazeMSS/OctoPrint-UICustomizer#52] opened 2021-01-04 16:41 UTC
## Description

I have the UI Customizer plugin installed but am confused.  The plugins "Main tabs" settings is showing "Themify plugin detected" ... but I do not have the Themify plugin installed.

**Plugins installed**
- Arc-Welder[arc_welder] v1.0.0+u.bb71e8f
- Bed Visualizer[bedlevelvisualizer] v1.0.0
- BetterHeaterTimeout[BetterHeaterTimeout] v1.3.0
- Dashboard[dashboard] v1.16.3
- Detailed Progress[detailedprogress] v0.2.6
- DisplayLayerProgress Plugin[DisplayLayerProgress] v1.24.0
- FileManager[filemanager] v0.1.4
- GcodeEditor[GcodeEditor] v0.2.10
- Marlin EEPROM Editor[eeprom_marlin] v3.0.0
- Marlin GCode Documentation[marlingcodedocumentation] v0.11.0
- Navbar Temperature Plugin[navbartemp] v0.14
- Preheat Button[preheat] v0.5.1
- PrintTimeGenius Plugin[PrintTimeGenius] v2.2.7
- Resource Monitor[resource_monitor] v0.2.7
- Simple Emergency Stop[simpleemergencystop] v1.0.4
- **UI Customizer[uicustomizer] v0.1.2.2**
- Z Probe Offset[z_probe_offset] v0.5

**UI Customizer settings**
- addWebCamZoom: true
- centerTopIcons: true
- compactMenu: true
- disableTermInactive: false
- fixedFooter: true
- fixedHeader: true
- fluidLayout: true
- gcodeFullWidth: false
- hideGraphBackground: true
- hideMainCam: false
- mainTabsCustomize: true
- navbarplugintempfix: true
- responsiveMode: true

**Software versions**
- OctoPrint 1.5.2
- Python 3.7.3
- OctoPi 0.18.0

**Browser**
- Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15

**Comment by LazeMSS** [comment] 2021-01-04 17:43
Not a bug in the code - but a left over from a previous bug - fixed by deleting plugin data.

**Closed** 2021-01-04 17:43 UTC
